#!/bin/bash
# Manual Docker Deployment Script for Render

echo "🐳 DOCKER DEPLOYMENT GUIDE FOR RENDER"
echo "======================================"
echo ""
echo "Since Render keeps defaulting to Python buildpack, follow these steps:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repo: BSRohit20/Infosys-Project"
echo "4. IMPORTANT: Select 'Docker' as the Environment (NOT Python!)"
echo "5. Use these settings:"
echo "   - Name: ai-hospitality-docker"
echo "   - Environment: Docker"
echo "   - Build Command: (leave blank)"
echo "   - Start Command: (leave blank, uses Dockerfile CMD)"
echo "   - Plan: Free"
echo ""
echo "6. Environment Variables to add:"
echo "   - ENVIRONMENT=production"
echo "   - SECRET_KEY=(generate new)"
echo ""
echo "7. Advanced Settings:"
echo "   - Health Check Path: /health"
echo "   - Dockerfile Path: ./Dockerfile"
echo ""
echo "8. Deploy!"
echo ""
echo "This will force Render to use our Python 3.11 Docker container"
echo "instead of their problematic Python 3.13 buildpack."
