[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "uvicorn app.main:app --host localhost --port 8000"
  port = 8000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
