services:
  - type: web
    name: ai-hospitality-system
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    branch: main
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SECRET_KEY
        generateValue: true
      - key: HF_API_TOKEN
        sync: false  # Set this manually in Render dashboard
      - key: SLACK_WEBHOOK_URL
        sync: false  # Set this manually in Render dashboard
      - key: PYTHON_VERSION
        value: "3.11"
    disk:
      name: model-cache
      mountPath: /opt/render/project/src/.cache
      sizeGB: 1
