services:
  - type: web
    name: ai-hospitality-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: HF_API_TOKEN
        sync: false  # Set this manually in Render dashboard
      - key: SLACK_WEBHOOK_URL
        sync: false  # Set this manually in Render dashboard
    disk:
      name: model-cache
      mountPath: /app/.cache
      sizeGB: 1
